security:
    oauth2:
        client:
            clientId: 0oad1lhrjze1NDb5V0h7
            clientSecret: Q-tlniEQMqgKtjxwr_TcGIFH9agMB23brmk5xMhR
            accessTokenUri: https://dev-960502.oktapreview.com/oauth2/default/v1/token
            userAuthorizationUri: https://dev-960502.oktapreview.com/oauth2/default/v1/authorize
            tokenName: oauth_token
            clientAuthenticationScheme: form
            issuer: https://dev-960502.oktapreview.com/oauth2/default
            scope: openid profile email
        resource:
            userInfoUri: https://dev-960502.oktapreview.com/oauth2/default/v1/userinfo